### ISSUE TITLE
Unknown errorCode "Invalid 'sameOriginWithAncestors' value" when signed in to Bitwarden browser extension

### ISSUE THREAD

**Issue by antonlydell** [bitwarden/passwordless-client-js#62]
## Background

When I try to register a passkey for an account on [Streamlit Passwordless](https://passwordless.streamlit.app) I get an error from the underlying javascript library [passwordless-client-js](https://github.com/bitwarden/passwordless-client-js) saying:

```json
{
'from': 'client',
'errorCode': 'unknown',
'title': "Invalid 'sameOriginWithAncestors' value",
} 
```

I get this error when I am signed in to the Bitwarden browser extension and when the extension is locked. It does not matter if I have a security key that can handle passkeys inserted into my machine or not. If I log out from the browser extension I can register a passkey with the security key without any issues. I have tested with both Firefox and Chromium and I get the same result. It works ok to register a passkey using the 1Password browser extension.

## Versions

- Firefox (128.0 (64-bitars) canonical-002 - 1.0)
  - [Bitwarden browser extension](https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/?browser=firefox):
     - Version : 2024.6.3
     - Server version : 2024.6.2
 
 - Chromium (126.0.6478.182 (Official Build) snap (64-bit))
   - [Bitwarden browser extension](https://chromewebstore.google.com/detail/bitwarden-l%C3%B6senordshanter/nngceckbapebfimnlniiiahkandclblb):
     - Version : 2024.6.2
     - Server version : 2024.6.2

## Steps to reproduce

1. Open Firefox or Chromium and install the Bitwarden browser extension.

2. Sign in to your Bitwarden account in the browser extension.

3. Navigate to [Streamlit Passwordless](https://passwordless.streamlit.app).

4. Enter a username in the "Username" field and press enter. 

5. Click the "Register" button.

6. Observe the error.

7. Lock the browser extension.

8. Repeat step 4-6.

9. Log out from the browser extension.

10. Repeat step 4-6.

11. Observe the WebAuthn pop up that appears.

**Comment by antonlydell** [comment]
Update:
I tested the workflow using the Bitwarden mobile app (version 2024.6.0 7846) on iOS (version 17.5.1) and it worked super smooth to both register and save a passkey to the Bitwarden account and then to use this saved passkey to sign in to the account.

**Comment by abergs** [comment]
Thanks for this report. This is a known bug related to Bitwarden browser extension and iframes, it's being tracked in that repo, so I will close this issue.

**Comment by antonlydell** [comment]
@abergs 
This issue still persists using Bitwarden Browser Extension:

- Version : 2024.10.0
- Server version : 2024.9.2
- Browser : Chromium
 
 Issue [Bitwarden Causing error when trying to add 2FA Credential in CheckMK](https://github.com/bitwarden/clients/issues/7551) is closed.
