### ISSUE TITLE
no typescript typedef files in compiled npm package

### ISSUE THREAD

**Issue by mehulbaid** [bitwarden/passwordless-client-js#85]
no typescript typedef files in compiled npm package.

It is causing issues with typescript, causing build time errors as no type definition files present.

Below is the screenshot of the node_modules folder for `@passwordlessdev/passwordless-client` (version: 1.2.1):

![image](https://github.com/user-attachments/assets/f8b273fc-d060-4181-baa7-decbf36232fd)

**Comment by abergs** [comment]
Thanks for reporting this, we'll investigate!

**Comment by abergs** [comment]
@mehulbaid Please take a look at 1.2.2 and see if that solves the problem you're having: https://github.com/bitwarden/passwordless-client-js/releases/tag/1.2.2
